### ISSUE TITLE
RSA 在线生成和使用

### ISSUE THREAD

**Issue by SpiritLing** [nextstarproject/tools-fe#12]
- [x] 调查是否可行
- [x] 选择具体的package
- [x] 执行添加工具
- [x] 生成RSA
- [x] 加解密RSA

**Comment by AlbertXiaoPeng** [comment]
可行性调查完成，可行，就是包比较旧
npm: https://www.npmjs.com/package/node-rsa
github: https://github.com/rzcoder/node-rsa

**Comment by AlbertXiaoPeng** [comment]
[#12issue 1-comment](https://github.com/nextstarproject/tools-fe/issues/12#issuecomment-1420278838)

node-rsa 无法实现，出现了 `Buffer` 错误

转为使用 jsencrypt
- npm: https://www.npmjs.com/package/jsencrypt
- github: https://github.com/travist/jsencrypt
