### ISSUE TITLE
新版本FrontEnd模板使用

### ISSUE THREAD

**Issue by SpiritLing** [nextstarproject/tools-fe#35]
新版本FrontEnd模板使用

- [x] 基础重构
- [x] 迁移已有功能
   - [x] 单向加密
   - [x] HMAC
   - [x] RSA 加解密
   - [x] 随机字符串
   - [x] UUID
   - [x] RSA 公私钥生成
- [ ] 新功能
   - [ ] 颜色转换

**Comment by SpiritLing** [comment]
可以完成
- #33 
- #32

**Comment by AlbertXiaoPeng** [comment]
加解密可以使用 https://developer.mozilla.org/zh-CN/docs/Web/API/SubtleCrypto 来尝试支持
